In [3]:
import pandas as pd

df = pd.read_csv("Final_Dataset_Human_Chimp.csv")

df.head()

,gene_id,gene_name,Mean_TPM_Tumor,Mean_TPM_Normal,Chimp_Expression
0,ENSG00000002330.14,BAD,20.6601,17.8573,84.61
1,ENSG00000003400.15,CASP10,28.0196,18.1117,72.97
2,ENSG00000015475.19,BID,12.6015,15.8005,87.79
3,ENSG00000026103.22,FAS,16.3736,11.3996,86.79
4,ENSG00000030110.13,BAK1,57.2943,22.0714,53.75

In [5]:
import numpy as np

df["Norm_Normal"] = df["Mean_TPM_Normal"] / df["Mean_TPM_Normal"].max()
df["Norm_Tumor"] = df["Mean_TPM_Tumor"] / df["Mean_TPM_Tumor"].max()
df["Norm_Chimp"] = df["Chimp_Expression"] / df["Chimp_Expression"].max()

In [8]:
def assign_tokens(x):
    if x <= 0.15:
        return 1
    elif x <= 0.3:
        return 2
    elif x <= 0.5:
        return 3
    elif x <= 0.7:
        return 4
    elif x <= 0.85:
        return 5
    else:
        return 6

In [12]:
df["Tokens_Normal"] = df["Norm_Normal"].apply(assign_tokens)
df["Tokens_Tumor"] = df["Norm_Tumor"].apply(assign_tokens)
df["Tokens_Chimp"] = df["Norm_Chimp"].apply(assign_tokens)

In [14]:
df[["gene_name","Tokens_Normal","Tokens_Tumor","Tokens_Chimp"]]

    gene_name  Tokens_Normal  Tokens_Tumor  Tokens_Chimp
0         BAD              1             2             6
1      CASP10              1             2             5
2         BID              1             1             6
3         FAS              1             2             6
4        BAK1              2             4             4
5       CASP8              1             2             5
6         BAX              3             4             5
7       MAPK1              4             6             6
8        XIAP              2             4             5
9       MAPK3              4             5             6
10      NFKB1              2             3             6
11      APAF1              1             1             5
12  TNFRSF10B              3             3             5
13     PIK3CA              1             1             6
14     CDKN1A              6             3             6
15      CASP9              1             2             4
16       MDM2              1             2             6
17      CASP6              1             2             5
18       TP53              2             3             4
19       AKT1              2             3             6
20        ATM              1             1             6
21      CASP3              2             3             5
22      CASP7              2             3             6
23       FADD              1             1             4
24     BCL2L1              4             6             4
25       BCL2              1             1             4
26       CYCS              2             4             5
27       RELA              3             5             5
28        ATR              1             1             4
29     DIABLO              1             1             5

In [16]:
df["Norm_Chimp"] = (df["Chimp_Expression"] - df["Chimp_Expression"].min()) / (df["Chimp_Expression"].max() - df["Chimp_Expression"].min())

In [18]:
df["Tokens_Chimp"] = df["Norm_Chimp"].apply(assign_tokens)

In [20]:
df[["gene_name","Tokens_Chimp"]]

    gene_name  Tokens_Chimp
0         BAD             5
1      CASP10             4
2         BID             6
3         FAS             6
4        BAK1             2
5       CASP8             4
6         BAX             4
7       MAPK1             6
8        XIAP             4
9       MAPK3             5
10      NFKB1             5
11      APAF1             4
12  TNFRSF10B             4
13     PIK3CA             6
14     CDKN1A             6
15      CASP9             1
16       MDM2             6
17      CASP6             4
18       TP53             1
19       AKT1             5
20        ATM             5
21      CASP3             4
22      CASP7             5
23       FADD             1
24     BCL2L1             1
25       BCL2             2
26       CYCS             3
27       RELA             4
28        ATR             1
29     DIABLO             3

In [22]:
final_tokens = df[["gene_name", "Tokens_Normal", "Tokens_Tumor", "Tokens_Chimp"]]

In [24]:
final_tokens = final_tokens.sort_values(by="gene_name")

In [26]:
final_tokens = final_tokens.reset_index(drop=True)

In [28]:
final_tokens.head()

  gene_name  Tokens_Normal  Tokens_Tumor  Tokens_Chimp
0      AKT1              2             3             5
1     APAF1              1             1             4
2       ATM              1             1             5
3       ATR              1             1             1
4       BAD              1             2             5

In [30]:
final_tokens.to_csv("Final_Tokens_Dataset.csv", index=False)